---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nest-api-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dev-nest-api-k8s
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-nest-api-k8s
    spec:
      containers:
        - name: dev-nest-api-k8s
          image: registry.digitalocean.com/resty-registry/dev-nest-api:latest
          ports:
            - containerPort: 3000
            - containerPort: 8081
          env:
            - name: REGION
              value: "EU"
            - name: LOGS_TOKEN
              value: "00d19095-bbe7-42c1-96c0-4d28c40eb17e"

---
apiVersion: v1
kind: Service
metadata:
  name: dev-nest-api-service
spec:
  sessionAffinity: ClientIP
  selector:
    app: dev-nest-api-k8s
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 3000
    - protocol: TCP
      name: ws
      port: 8081
      targetPort: 8081
