---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nest-api-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dev-nest-api-k8s
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-nest-api-k8s
    spec:
      containers:
        - name: dev-nest-api-k8s
          image: registry.digitalocean.com/resty-registry/dev-nest-api:latest
          ports:
            - containerPort: 3000
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /api/health/check
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 30"]
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: dev-nest-api-service
spec:
  selector:
    app: dev-nest-api-k8s
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 3000
    - protocol: TCP
      name: ws
      port: 8081
      targetPort: 8081
