apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "64m"
  name: ingress-service
  namespace: default
spec:
  tls:
    - hosts:
        - dev-api.resty.od.ua
  rules:
    - host: dev-api.resty.od.ua
      http:
        paths:
          - backend:
              service:
                name: app-sockets-cluster-ip-service
                port:
                  number: 3003
            path: /socket.io/?(.*)
            pathType: Prefix
