# Cluster Role bindings for Agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spm-agent-nodejs
  labels:
    app: spm-agent-nodejs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spm-agent-nodejs
subjects:
  - kind: ServiceAccount
    name: spm-agent-nodejs
    namespace: default
---
# Cluster Role for Agent
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spm-agent-nodejs
  labels:
    app: spm-agent-nodejs
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - get
      - watch
---
# Service Account for Agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spm-agent-nodejs
  labels:
    app: spm-agent-nodejs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-nest-api-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dev-nest-api-k8s
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-nest-api-k8s
    spec:
      serviceAccountName: spm-agent-nodejs
      containers:
        - name: dev-nest-api-k8s
          image: registry.digitalocean.com/resty-registry/dev-nest-api:latest
          ports:
            - containerPort: 3000
            - containerPort: 8081
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONITORING_TOKEN
              value: "0f7fa2db-cd12-4a54-acd9-0aaafa0513b7"
            - name: SPM_RECEIVER_URL
              value: "https://spm-receiver.eu.sematext.com/receiver/v1"
            - name: LOGS_RECEIVER_URL
              value: "https://logsene-receiver.eu.sematext.com"
            - name: EVENTS_RECEIVER_URL
              value: "https://event-receiver.eu.sematext.com"
            - name: INFRA_TOKEN
              value: "e924b561-5d45-4be5-853d-5f3ce4e84fbb"
          readinessProbe:
            httpGet:
              path: /api/health/check
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 120"]
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: dev-nest-api-service
spec:
  selector:
    app: dev-nest-api-k8s
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 3000
    - protocol: TCP
      name: ws
      port: 8081
      targetPort: 8081
