---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-nest-api-k8s-deployment
spec:
  selector:
    matchLabels:
      app: prod-nest-api-k8s
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod-nest-api-k8s
    spec:
      containers:
        - name: prod-nest-api-k8s
          image: registry.digitalocean.com/resty-registry/prod-nest-api:latest
          ports:
            - containerPort: 3000
            - containerPort: 8081
          env:
            - name: REGION
              value: "EU"
            - name: LOGS_TOKEN
              value: "00d19095-bbe7-42c1-96c0-4d28c40eb17e"
          readinessProbe:
            httpGet:
              path: /api/health/check
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 120"]
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: prod-nest-api-service
spec:
  selector:
    app: prod-nest-api-k8s
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 3000
    - protocol: TCP
      name: ws
      port: 8081
      targetPort: 8081
