version: "3.8"
services:
  nest-api-database:
    image: postgres:latest
    container_name: nest-api-database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "nest-api-database"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - nest-api-database:/var/lib/postgresql/data
volumes:
  nest-api-database:
