export enum ORDERS_EVENTS {
	CREATED = "ORDER_CREATED",
	CLOSED = "ORDER_CLOSED",
	CANCELED = "ORDER_CANCELED",
	CONFIRM = "ORDER_CONFIRM",
	REJECTED = "ORDER_REJECTED",
	APPROVED = "ORDER_APPROVED",
	WAITING_FOR_MANUAL_PAY = "ORDER_WAITING_FOR_MANUAL_PAY",
	USER_ADDED = "ORDER_USER_ADDED",
	PTO_APPROVED = "ORDER_PTO_APPROVED",
	PTO_REJECTED = "ORDER_PTO_REJECTED",
	TABLE_ADDED = "ORDER_TABLE_ADDED",
	REQUEST_TO_CONFIRM = "ORDER_REQUEST_TO_CONFIRM",
	TABLE_REMOVED = "ORDER_TABLE_REMOVED"
}
