export enum ORDERS_EVENTS {
	CREATED = "CREATED",
	CLOSED = "CLOSED",
	CANCELED = "CANCELED",
	CONFIRM = "CONFIRM",
	REJECTED = "REJECTED",
	APPROVED = "APPROVED",
	WAITING_FOR_MANUAL_PAY = "WAITING_FOR_MANUAL_PAY",
	USER_ADDED = "USER_ADDED",
	PTO_APPROVED = "PTO_APPROVED",
	PTO_REJECTED = "PTO_REJECTED",
	TABLE_ADDED = "TABLE_ADDED",
	REQUEST_TO_CONFIRM = "REQUEST_TO_CONFIRM",
	TABLE_REMOVED = "TABLE_REMOVED"
}
