export enum OrderStatusEnum {
	// "OPENED" = "OPENED",
	// "CLOSED" = "CLOSED",
	// "UNPAID" = "UNPAID",
	// "PAID" = "PAID"

	CREATED = "CREATED",
	CANCEL = "CANCEL",
	CLOSED = "CLOSED",
	APPROVED = "APPROVED",
	REJECTED = "REJECTED",
	REQUEST_TO_CONFIRM = "REQUEST_TO_CONFIRM"
}
